### ISSUE TITLE
Make sure all provided sketch folders work as expected

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/sketchFinder#1]
Assigned to @waldo-withers & @spoiledPiggy

Please make sure our tool detects the exact same projects and libraries as the Arduino IDE 1.0.5 does.

Use the provided sketch folder (all of them) found in the VM.
As for the libraries, you can use the Import library button from the "Sketch" menu from the Arduino IDE.

**Comment by spoiledPiggy** [comment]
Yes, all the sketch folders work as expected.  
 Sorry, we were not familiar with the github "issue" functions, so we didn't give response.
