### ISSUE TITLE
Provide a list of the ignored files

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/sketchFinder#2]
Assigned to @waldo-withers & @spoiledPiggy 

Make the tool provide a list of the ignored files from every sketch folder. 
Also report the directories in which the ignored files belong.
Make sure we don't make any changes in the code we used from the Arduino repository.

**Comment by spoiledPiggy** [comment]
Our command line application has the option to display all the ignored files and the directories they belong to.
