### ISSUE TITLE
Arduino 1.6 compatible sketchFinder

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/sketchFinder#3]
Assigned to @waldo-withers & @spoiledPiggy 

Create a new branch in the repo and update the code of the sketchFinder tool from the Arduino 1.6 branch.

Make sure we implement the same features that are implemented in the current version of the sketchFinder tool.

**Comment by spoiledPiggy** [comment]
I have created a new brach for version 1.6.3(the newest version) now.
