### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by toubou91** [codebendercc/sketchFinder#5]
I get the following error, while trying to compile the sources, using JDK 1.8

<code>
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The method sort(new Comparator<File>(){}) is undefined for the type List<File>
	The method sort(new Comparator<SketchFinder.FileTree>(){}) is undefined for the type List<SketchFinder.FileTree>

	at SketchFinder$FileTree.toString(SketchFinder.java:331)
	at SketchFinder$FileTree.toString(SketchFinder.java:320)
	at java.lang.String.valueOf(String.java:2854)
	at java.io.PrintStream.println(PrintStream.java:821)
	at SketchFinder.main(SketchFinder.java:128) 
</code>

**Comment by spoiledPiggy** [comment]
Hi,
I think you should use SketchFinder.jar file in ArduinoV1.6 branch, there's another sketchfinder.jar file in that repo, sorry for the confusion. I tested and it worked well.

**Comment by tzikis** [comment]
Hey Wen,
Actually, we are trying to compile this and add some stuff to the program's output. Any chance you could give us a few hints?

Also, could you please update us on the current status of each of the two branches, and their differences?

Thanks,
Tzikis

**Comment by toubou91** [comment]
@spoiledPiggy I cannot verify this easily, as you haven't provided either documentation or just some very basic samples.

Could you please fix this? It will help future users and contributors of the project.

**Comment by spiliot** [comment]
I believe this issue is resolved with what is explained in #6 so I'm closing this.
